package com.example.cmput301_app.model;

import java.util.ArrayList;
import com.google.firebase.Timestamp;

import java.util.List;

/**
 * Represents an event in the application.
 *
 * An event is created by an organizer and contains all details relevant
 * to entrants browsing and joining the waiting list. Each event has a
 * registration window, an optional waiting list cap, a capacity for
 * confirmed attendees, and an associated QR code for entrant discovery.
 *
 * Event-specific settings such as geolocation requirements and waiting
 * list limits are stored here rather than on the Organizer class, as
 * these settings are unique to each individual event.
 *
 * Outstanding issues:
 * - QR code generation logic is handled externally and the result is
 *   stored here as a string. Generation implementation is not yet complete.
 * - Date fields use Firebase Timestamp for Firestore compatibility.
 */
public class Event {

    /** Unique identifier for this event, generated by Firestore */
    private String eventId;

    /** Display name of the event */
    private String name;

    /** Description of the event providing details to entrants */
    private String description;

    /** Physical location where the event takes place */
    private String location;

    /** Date and time the event takes place */
    private Timestamp date;

    /** Cost in dollars to attend the event */
    private double price;

    /** Maximum number of confirmed attendees allowed */
    private int capacity;

    /** Date and time when registration opens */
    private Timestamp registrationOpen;

    /** Date and time when registration closes */
    private Timestamp registrationClose;

    /** Device ID of the organizer who created this event */
    private String organizerId;

    /** Firebase Storage download URL for the event poster image */
    private String posterUrl;

    /** QR code string that links entrants to this event's details page */
    private String qrCode;

    /** Whether entrants are required to provide geolocation when joining the waiting list */
    private boolean geolocationEnabled;

    /**
     * Maximum number of entrants allowed on the waiting list.
     * A value of -1 indicates the waiting list is unlimited.
     */
    private int waitingListLimit;

    /** List of device IDs of entrants currently on the waiting list */
    private List<String> waitingListIds;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Default no-argument constructor required for Firebase deserialization.
     */
    public Event() {
        this.waitingListIds = new ArrayList<>();
        this.waitingListLimit = -1;
        this.geolocationEnabled = false;
    }

    /**
     * Constructs an Event with all required fields.
     * Waiting list is unlimited by default and geolocation is disabled by default.
     *
     * @param eventId           the unique identifier for this event
     * @param name              the display name of the event
     * @param description       the description of the event
     * @param location          the physical location of the event
     * @param date              the date and time the event takes place
     * @param price             the cost to attend
     * @param capacity          the maximum number of confirmed attendees
     * @param registrationOpen  the date and time registration opens
     * @param registrationClose the date and time registration closes
     * @param organizerId       the device ID of the organizer who created this event
     */
    public Event(String eventId, String name, String description, String location,
                 Timestamp date, double price, int capacity,
                 Timestamp registrationOpen, Timestamp registrationClose, String organizerId) {
        this.eventId = eventId;
        this.name = name;
        this.description = description;
        this.location = location;
        this.date = date;
        this.price = price;
        this.capacity = capacity;
        this.registrationOpen = registrationOpen;
        this.registrationClose = registrationClose;
        this.organizerId = organizerId;
        this.waitingListIds = new ArrayList<>();
        this.waitingListLimit = -1;
        this.geolocationEnabled = false;
    }

    // -------------------------------------------------------------------------
    // Registration Window Methods
    // -------------------------------------------------------------------------

    /**
     * Returns whether the registration window is currently open.
     * Registration is open if the current time is after registrationOpen
     * and before registrationClose.
     *
     * @return true if registration is currently open, false otherwise
     */
    public boolean isRegistrationOpen() {
        Timestamp now = Timestamp.now();

        return now.compareTo(registrationOpen) > 0 && now.compareTo(registrationClose) < 0;
    }

    // -------------------------------------------------------------------------
    // Waiting List Methods
    // -------------------------------------------------------------------------

    /**
     * Returns whether the waiting list has reached its cap.
     * Always returns false if the waiting list limit is set to -1 (unlimited).
     *
     * @return true if the waiting list is full, false otherwise
     */
    public boolean isWaitingListFull() {
        if (waitingListLimit == -1) {
            return false;
        }
        return waitingListIds.size() >= waitingListLimit;
    }

    /**
     * Adds an entrant to the waiting list by their device ID.
     * Does nothing if the entrant is already on the waiting list
     * or if the waiting list is full.
     *
     * @param deviceId the device ID of the entrant to add
     */
    public void addToWaitingList(String deviceId) {
        if (!waitingListIds.contains(deviceId) && !isWaitingListFull()) {
            waitingListIds.add(deviceId);
        }
    }

    /**
     * Removes an entrant from the waiting list by their device ID.
     * Does nothing if the entrant is not on the waiting list.
     *
     * @param deviceId the device ID of the entrant to remove
     */
    public void removeFromWaitingList(String deviceId) {
        waitingListIds.remove(deviceId);
    }

    /**
     * Returns whether a given entrant is currently on the waiting list.
     *
     * @param deviceId the device ID of the entrant to check
     * @return true if the entrant is on the waiting list, false otherwise
     */
    public boolean isOnWaitingList(String deviceId) {
        return waitingListIds.contains(deviceId);
    }

    /**
     * Returns the current number of entrants on the waiting list.
     *
     * @return the size of the waiting list
     */
    public int getWaitingListCount() {
        return waitingListIds.size();
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique identifier for this event.
     *
     * @return the event ID string
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Sets the unique identifier for this event.
     *
     * @param eventId the event ID to assign
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * Returns the display name of the event.
     *
     * @return the event name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name of the event.
     *
     * @param name the name to assign
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description of the event.
     *
     * @return the event description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the event.
     *
     * @param description the description to assign
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the physical location of the event.
     *
     * @return the event location
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the physical location of the event.
     *
     * @param location the location to assign
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Returns the date and time the event takes place.
     *
     * @return the event date
     */
    public Timestamp getDate() {
        return date;
    }

    /**
     * Sets the date and time the event takes place.
     *
     * @param date the date to assign
     */
    public void setDate(Timestamp date) {
        this.date = date;
    }

    /**
     * Returns the cost to attend the event.
     *
     * @return the event price
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the cost to attend the event.
     *
     * @param price the price to assign
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * Returns the maximum number of confirmed attendees allowed.
     *
     * @return the event capacity
     */
    public int getCapacity() {
        return capacity;
    }

    /**
     * Sets the maximum number of confirmed attendees allowed.
     *
     * @param capacity the capacity to assign
     */
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    /**
     * Returns the date and time when registration opens.
     *
     * @return the registration open date
     */
    public Timestamp getRegistrationOpen() {
        return registrationOpen;
    }

    /**
     * Sets the date and time when registration opens.
     *
     * @param registrationOpen the registration open date to assign
     */
    public void setRegistrationOpen(Timestamp registrationOpen) {
        this.registrationOpen = registrationOpen;
    }

    /**
     * Returns the date and time when registration closes.
     *
     * @return the registration close date
     */
    public Timestamp getRegistrationClose() {
        return registrationClose;
    }

    /**
     * Sets the date and time when registration closes.
     *
     * @param registrationClose the registration close date to assign
     */
    public void setRegistrationClose(Timestamp registrationClose) {
        this.registrationClose = registrationClose;
    }

    /**
     * Returns the device ID of the organizer who created this event.
     *
     * @return the organizer's device ID
     */
    public String getOrganizerId() {
        return organizerId;
    }

    /**
     * Sets the device ID of the organizer who created this event.
     *
     * @param organizerId the organizer device ID to assign
     */
    public void setOrganizerId(String organizerId) {
        this.organizerId = organizerId;
    }

    /**
     * Returns the Firebase Storage download URL for the event poster image.
     *
     * @return the poster URL string, or null if no poster has been uploaded
     */
    public String getPosterUrl() {
        return posterUrl;
    }

    /**
     * Sets the Firebase Storage download URL for the event poster image.
     *
     * @param posterUrl the poster URL to assign, or null to clear it
     */
    public void setPosterUrl(String posterUrl) {
        this.posterUrl = posterUrl;
    }

    /**
     * Returns the QR code string that links entrants to this event's details page.
     *
     * @return the QR code string, or null if not yet generated
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * Sets the QR code string for this event.
     *
     * @param qrCode the QR code string to assign
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    /**
     * Returns whether entrants are required to provide geolocation when joining the waiting list.
     *
     * @return true if geolocation is required, false otherwise
     */
    public boolean isGeolocationEnabled() {
        return geolocationEnabled;
    }

    /**
     * Sets whether entrants are required to provide geolocation when joining the waiting list.
     *
     * @param geolocationEnabled true to require geolocation, false to disable it
     */
    public void setGeolocationEnabled(boolean geolocationEnabled) {
        this.geolocationEnabled = geolocationEnabled;
    }

    /**
     * Returns the maximum number of entrants allowed on the waiting list.
     * A value of -1 indicates the waiting list is unlimited.
     *
     * @return the waiting list limit, or -1 if unlimited
     */
    public int getWaitingListLimit() {
        return waitingListLimit;
    }

    /**
     * Sets the maximum number of entrants allowed on the waiting list.
     * Pass -1 to set the waiting list as unlimited.
     *
     * @param waitingListLimit the cap to assign, or -1 for unlimited
     */
    public void setWaitingListLimit(int waitingListLimit) {
        this.waitingListLimit = waitingListLimit;
    }

    /**
     * Returns the list of device IDs of entrants currently on the waiting list.
     *
     * @return list of entrant device IDs
     */
    public List<String> getWaitingListIds() {
        return waitingListIds;
    }

    /**
     * Sets the list of device IDs of entrants currently on the waiting list.
     *
     * @param waitingListIds the list of device IDs to assign
     */
    public void setWaitingListIds(List<String> waitingListIds) {
        this.waitingListIds = waitingListIds;
    }
}
