package com.example.cmput301_app.model;

import com.google.firebase.Timestamp;

/**
 * Represents an event poster in the application.
 *
 * A poster is uploaded by an organizer and is associated with a specific event.
 * It serves as a dedicated data object for managing event poster images separately
 * from the Event class, allowing admins to browse and remove images independently
 * of event management.
 *
 * When a poster is created or removed, PosterDB is responsible for keeping the
 * posterUrl field on the corresponding Event document in Firestore in sync.
 * Specifically:
 * - When a poster is uploaded, PosterDB creates the Poster document and updates
 *   the posterUrl field on the associated Event document.
 * - When a poster is removed, PosterDB deletes the Poster document, removes the
 *   image from Firebase Storage, and clears the posterUrl field on the associated
 *   Event document.
 *
 * Outstanding issues:
 * - Image upload and deletion logic is handled entirely by PosterDB and Firebase
 *   Storage. This class models the poster data only.
 */
public class Poster {

    /** Unique identifier for this poster, generated by Firestore */
    private String posterId;

    /**
     * The ID of the event this poster belongs to.
     * Used by PosterDB to keep the posterUrl field on the Event document in sync.
     */
    private String eventId;

    /** The device ID of the organizer who uploaded this poster */
    private String organizerId;

    /**
     * Firebase Storage download URL for the poster image.
     * This value is also stored on the associated Event document's posterUrl field,
     * kept in sync by PosterDB.
     */
    private String imageUrl;

    /** The timestamp when this poster was uploaded */
    private Timestamp uploadTimestamp;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Default no-argument constructor required for Firebase deserialization.
     */
    public Poster() {}

    /**
     * Constructs a Poster with all required fields.
     *
     * @param posterId        the unique identifier for this poster
     * @param eventId         the ID of the event this poster belongs to
     * @param organizerId     the device ID of the organizer who uploaded this poster
     * @param imageUrl        the Firebase Storage download URL for the poster image
     * @param uploadTimestamp the time this poster was uploaded
     */
    public Poster(String posterId, String eventId, String organizerId,
                  String imageUrl, Timestamp uploadTimestamp) {
        this.posterId = posterId;
        this.eventId = eventId;
        this.organizerId = organizerId;
        this.imageUrl = imageUrl;
        this.uploadTimestamp = uploadTimestamp;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique identifier for this poster.
     *
     * @return the poster ID string
     */
    public String getPosterId() {
        return posterId;
    }

    /**
     * Sets the unique identifier for this poster.
     *
     * @param posterId the poster ID to assign
     */
    public void setPosterId(String posterId) {
        this.posterId = posterId;
    }

    /**
     * Returns the ID of the event this poster belongs to.
     * Used by PosterDB to keep the posterUrl field on the Event document in sync.
     *
     * @return the event ID string
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Sets the ID of the event this poster belongs to.
     *
     * @param eventId the event ID to assign
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * Returns the device ID of the organizer who uploaded this poster.
     *
     * @return the organizer device ID string
     */
    public String getOrganizerId() {
        return organizerId;
    }

    /**
     * Sets the device ID of the organizer who uploaded this poster.
     *
     * @param organizerId the organizer device ID to assign
     */
    public void setOrganizerId(String organizerId) {
        this.organizerId = organizerId;
    }

    /**
     * Returns the Firebase Storage download URL for the poster image.
     * This value is also stored on the associated Event document's posterUrl field,
     * kept in sync by PosterDB.
     *
     * @return the image URL string, or null if not yet uploaded
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Sets the Firebase Storage download URL for the poster image.
     *
     * @param imageUrl the image URL to assign
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Returns the timestamp when this poster was uploaded.
     *
     * @return the upload Timestamp
     */
    public Timestamp getUploadTimestamp() {
        return uploadTimestamp;
    }

    /**
     * Sets the timestamp when this poster was uploaded.
     *
     * @param uploadTimestamp the upload Timestamp to assign
     */
    public void setUploadTimestamp(Timestamp uploadTimestamp) {
        this.uploadTimestamp = uploadTimestamp;
    }
}