package com.example.cmput301_app;

/**
 * Represents an administrator in the application.
 *
 * An admin is a privileged user who manages the infrastructure of the app.
 * Unlike entrants and organizers, admins are not identified by their device
 * and do not go through the standard registration flow. Admins are pre-defined
 * and authenticate via email and password through Firebase Authentication.
 *
 * Admin does not extend Profile as admins have a fundamentally different
 * identity and authentication model from entrants and organizers. Fields
 * such as device ID, phone number, geolocation, and profile image are not
 * applicable to the admin role.
 *
 * All admin actions such as removing events, profiles, images, organizers,
 * and browsing notification history are handled by AdminDB, which coordinates
 * across EventDB, EntrantDB, OrganizerDB, PosterDB, and NotificationDB
 * as needed.
 *
 * Outstanding issues:
 * - Admin authentication flow and entry point in the app are not yet implemented.
 * - Admin accounts are expected to be created directly in Firebase rather than
 *   through the app's registration flow.
 */
public class Admin {

    /** Unique identifier for this admin, generated by Firestore */
    private String adminId;

    /** Email address used by the admin to log in via Firebase Authentication */
    private String email;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Default no-argument constructor required for Firebase deserialization.
     */
    public Admin() {}

    /**
     * Constructs an Admin with all required fields.
     *
     * @param adminId the unique identifier for this admin
     * @param email   the email address used to log in
     */
    public Admin(String adminId, String email) {
        this.adminId = adminId;
        this.email = email;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique identifier for this admin.
     *
     * @return the admin ID string
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * Sets the unique identifier for this admin.
     *
     * @param adminId the admin ID to assign
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    /**
     * Returns the email address used by the admin to log in.
     *
     * @return the admin email string
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address used by the admin to log in.
     *
     * @param email the email to assign
     */
    public void setEmail(String email) {
        this.email = email;
    }
}