package com.example.cmput301_app;

import com.google.firebase.Timestamp;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a notification in the application.
 *
 * A notification is sent to one or more entrants and is associated with
 * a specific event. Notifications can be sent automatically by the system
 * as a result of lottery draws, or manually by an organizer as a broadcast
 * message to a group of entrants.
 *
 * This class handles only the local state of a notification. All persistence
 * to Firebase is handled by NotificationDB.
 *
 * Outstanding issues:
 * - Actual push notification delivery via Firebase Cloud Messaging (FCM)
 *   is not yet implemented. This class models the notification data only.
 */
public class Notification {

    /**
     * Enum representing the type of notification being sent.
     */
    public enum NotificationType {
        /** Entrant was selected in the lottery draw */
        LOTTERY_WIN,
        /** Entrant was not selected in the lottery draw */
        LOTTERY_LOSS,
        /** Organizer sent a custom broadcast message to a group of entrants */
        ORGANIZER_BROADCAST,
        /** Entrant's invitation was revoked by the organizer */
        INVITATION_CANCELLED
    }

    /** Unique identifier for this notification, generated by Firestore */
    private String notificationId;

    /** The ID of the event this notification is associated with */
    private String eventId;

    /** The device ID of the organizer who sent this notification */
    private String organizerId;

    /** List of device IDs of entrants this notification was sent to */
    private List<String> recipientIds;

    /** The content of the notification message */
    private String message;

    /** The type of this notification */
    private NotificationType type;

    /** The timestamp when this notification was sent */
    private Timestamp timestamp;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Default no-argument constructor required for Firebase deserialization.
     */
    public Notification() {
        this.recipientIds = new ArrayList<>();
    }

    /**
     * Constructs a Notification with all required fields.
     *
     * @param notificationId the unique identifier for this notification
     * @param eventId        the ID of the event this notification is associated with
     * @param organizerId    the device ID of the organizer who sent this notification
     * @param message        the content of the notification message
     * @param type           the type of this notification
     * @param timestamp      the time this notification was sent
     */
    public Notification(String notificationId, String eventId, String organizerId,
                        String message, NotificationType type, Timestamp timestamp) {
        this.notificationId = notificationId;
        this.eventId = eventId;
        this.organizerId = organizerId;
        this.message = message;
        this.type = type;
        this.timestamp = timestamp;
        this.recipientIds = new ArrayList<>();
    }

    // -------------------------------------------------------------------------
    // Recipient Methods
    // -------------------------------------------------------------------------

    /**
     * Adds an entrant to the recipient list.
     * Does nothing if the entrant is already a recipient.
     *
     * @param deviceId the device ID of the entrant to add
     */
    public void addRecipient(String deviceId) {
        if (!recipientIds.contains(deviceId)) {
            recipientIds.add(deviceId);
        }
    }

    /**
     * Removes an entrant from the recipient list.
     * Does nothing if the entrant is not a recipient.
     *
     * @param deviceId the device ID of the entrant to remove
     */
    public void removeRecipient(String deviceId) {
        recipientIds.remove(deviceId);
    }

    /**
     * Returns whether a given entrant is a recipient of this notification.
     *
     * @param deviceId the device ID of the entrant to check
     * @return true if the entrant is a recipient, false otherwise
     */
    public boolean hasRecipient(String deviceId) {
        return recipientIds.contains(deviceId);
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique identifier for this notification.
     *
     * @return the notification ID string
     */
    public String getNotificationId() {
        return notificationId;
    }

    /**
     * Sets the unique identifier for this notification.
     *
     * @param notificationId the notification ID to assign
     */
    public void setNotificationId(String notificationId) {
        this.notificationId = notificationId;
    }

    /**
     * Returns the ID of the event this notification is associated with.
     *
     * @return the event ID string
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Sets the ID of the event this notification is associated with.
     *
     * @param eventId the event ID to assign
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * Returns the device ID of the organizer who sent this notification.
     *
     * @return the organizer device ID string
     */
    public String getOrganizerId() {
        return organizerId;
    }

    /**
     * Sets the device ID of the organizer who sent this notification.
     *
     * @param organizerId the organizer device ID to assign
     */
    public void setOrganizerId(String organizerId) {
        this.organizerId = organizerId;
    }

    /**
     * Returns the list of device IDs of entrants this notification was sent to.
     *
     * @return list of recipient device IDs
     */
    public List<String> getRecipientIds() {
        return recipientIds;
    }

    /**
     * Sets the list of device IDs of entrants this notification was sent to.
     *
     * @param recipientIds the list of recipient device IDs to assign
     */
    public void setRecipientIds(List<String> recipientIds) {
        this.recipientIds = recipientIds;
    }

    /**
     * Returns the content of the notification message.
     *
     * @return the message string
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the content of the notification message.
     *
     * @param message the message string to assign
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Returns the type of this notification.
     *
     * @return the NotificationType enum value
     */
    public NotificationType getType() {
        return type;
    }

    /**
     * Sets the type of this notification.
     *
     * @param type the NotificationType enum value to assign
     */
    public void setType(NotificationType type) {
        this.type = type;
    }

    /**
     * Returns the timestamp when this notification was sent.
     *
     * @return the Timestamp of when the notification was sent
     */
    public Timestamp getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the timestamp when this notification was sent.
     *
     * @param timestamp the Timestamp to assign
     */
    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }
}
